name: Build OrangeFox Tecno LG6n Final

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 1. Checkout Bahan
        uses: actions/checkout@v4

      - name: 2. Install Alat Tempur
        run: |
          sudo apt-get update
          sudo apt-get install -y bc build-essential zip curl libstdc++6 git wget python3 gcc g++ libssl-dev repo
          
      - name: 3. Sync Source OrangeFox (Pusat Kode)
        run: |
          mkdir fox && cd fox
          repo init --depth=1 -u https://github.com -b fox_12.1
          repo sync -j$(nproc --all) --force-sync --no-clone-bundle --no-tags

      - name: 4. Ekstrak Device Tree Kamu
        run: |
          mkdir -p fox/device/tecno/LG6n
          unzip tree.zip -d fox/device/tecno/LG6n
          # Cek isi biar yakin filenya gak nyasar
          ls -R fox/device/tecno/LG6n

      - name: 5. Mulai Compile (Masak)
        run: |
          cd fox
          source build/envsetup.sh
          export ALLOW_MISSING_DEPENDENCIES=true
          export FOX_VERSION="R11.1_Unofficial"
          export LC_ALL="C"
          # Sesuai identitas device kamu: omni_TECNO-LG6n
          lunch omni_TECNO-LG6n-eng
          mka recoveryimage -j$(nproc --all)

      - name: 6. Upload Hasil (.img)
        uses: actions/upload-artifact@v4
        with:
          name: OrangeFox-Tecno-LG6n
          path: fox/out/target/product/LG6n/*.img
